name: e2e

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL to test"
        required: true
        default: "https://ontowave.com"

jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -r tests/e2e/requirements.txt
          python -m playwright install --with-deps
      - name: Run e2e
        run: pytest -q tests/e2e -k e2e --base-url "${{ inputs.base_url }}"