name: Roadmap setup

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Nom du Projet GitHub (Classic) à créer/associer"
        required: false
        default: "OntoWave Roadmap"
  push:
    paths:
      - '.github/seed-roadmap.txt'

jobs:
  seed:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Roadmap issue exists
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Roadmap: idées et améliorations"
          content-filepath: .github/ISSUE_TEMPLATE/roadmap.md
          labels: roadmap,enhancement
          assignees: ""
      - name: Optionally create/attach Project (classic) via gh CLI
        if: github.event.inputs.project_name != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Trying to create/ensure project: ${{ github.event.inputs.project_name }}"
          gh api repos/${{ github.repository }}/projects --method GET -H "Accept: application/vnd.github.inertia-preview+json" | jq -r '.[].name' | grep -qx "${{ github.event.inputs.project_name }}" || \
          gh api repos/${{ github.repository }}/projects --method POST -H "Accept: application/vnd.github.inertia-preview+json" -f name='${{ github.event.inputs.project_name }}' || true
